### ISSUE TITLE
Please add function to change subtitles to f.e. german!

### ISSUE THREAD

**Issue by sammox2016** [remixz/umi#1]
This is very important because it's not that fun to watch everything together but only in english subtitles :c

**Comment by remixz** [comment]
Hey! I've just added a language setting on https://umi.bruggie.com/settings (though it won't show up until Umi prompts you to update – should only take a few seconds after you open the page). I never even thought people would be using Umi from a different country than mine. 😉  Thanks for opening this issue!

**Comment by sammox2016** [comment]
No problem! :) Yeah, I want to watch anime together with my friends but with german subtitles because not all of them can speak english fluently ._. I like your work, keep it up! :)

**Comment by sammox2016** [comment]
If you want, it would be nice if I can help you with your site ^^ In topics like design ;)
