### ISSUE TITLE
Feature Request: AniList integration

### ISSUE THREAD

**Issue by der-coder** [remixz/umi#23]
Current connection services only consider MyAnimeList. AniList provides a functional API and a considerable userbase as well. Any chance to add support for AniList users?

**Comment by remixz** [comment]
Great idea! I've integrated AniList as of https://github.com/remixz/umi/commit/8e9a3509ec2bc08b80b6c905dec5415afa479a50. You can sign in and enable it here: https://umi.party/settings Just make sure to wait for the update to complete.
