### ISSUE TITLE
Keep getting "this room has expired" error

### ISSUE THREAD

**Issue by NotAsianDave** [remixz/umi#3]
whenever me and my friends try to join a room, were met with a message that says " this room has expired" and only allow us to go back to the dashboard.

**Comment by remixz** [comment]
Hey, thanks for filing this issue! It looks like the watch together server's host had a deployment glitch. I just restarted it, and it's working for me now. Can you refresh, create a new room, and try again?

**Comment by NotAsianDave** [comment]
Thank you for such a quick response! Its all seems fine now.

**Comment by remixz** [comment]
👍 Perfect! I was probably going to use the player soon anyway... 😂
