### ISSUE TITLE
Umi Enabler requires update for new content urls

### ISSUE THREAD

**Issue by Fireye00** [remixz/umi#30]
Howdy,
I've had some issues over the past month, where some videos refuse to play due to CORS issues.  The problem seemed similar to #18, so I tried to install the Umi Enabler addon for Firefox.  Unfortunately that didn't solve my issues, but I did notice that Umi Enabler is limited to working on `*.vrv.co/*` and `*.dlvr1.net/*`, while the content that's being blocked now appears to be served under the pl.crunchyroll.com domain.

Can you update the Umi Enabler addon to support the new domain?  Below is a cors block message from FF with the relevant info:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pl.crunchyroll.com/evs1/6e28d444ede84d4bf5ee236b826bdac3/assets/0c0f7ace8d9e0bc3baadb04bfdfc397e_,3860678.mp4,3860679.mp4,3860677.mp4,3860676.mp4,3860675.mp4,.urlset/master.m3u8?Policy=<policy>&Signature=<sig>&Key-Pair-Id=<keypair>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

**Comment by remixz** [comment]
👋 Thanks for reporting this! I was able to fix it without updating the extension, and just in Umi itself. I hope. Can you try playing an episode again, and let me know if it works?

**Comment by ThatSinisterSylveon** [comment]
I can confirm it is working now

**Comment by Fireye00** [comment]
Confirmed OK here as well, thanks for the quick fix!

**Comment by leonardo-rem** [comment]
Im still haveing this problem
